"""empty message

Revision ID: 037f05db5e84
Revises: 1dcc82b4678d
Create Date: 2022-12-31 11:58:42.484631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '037f05db5e84'
down_revision = '1dcc82b4678d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_file_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_file_key')
    # ### end Alembic commands ###
