"""empty message

Revision ID: 56f943e4e0c0
Revises: ebc009b5430e
Create Date: 2023-02-07 18:21:10.644408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56f943e4e0c0'
down_revision = 'ebc009b5430e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
