"""empty message

Revision ID: d4ba1eb79294
Revises: 56f943e4e0c0
Create Date: 2023-02-07 18:23:17.463197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4ba1eb79294'
down_revision = '56f943e4e0c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
