"""empty message

Revision ID: ebc009b5430e
Revises: 79ed0da11d18
Create Date: 2023-02-07 18:16:51.547907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebc009b5430e'
down_revision = '79ed0da11d18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'board', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'board', type_='unique')
    # ### end Alembic commands ###
